### ISSUE TITLE
Missing classes while importing source

### ISSUE THREAD

**Issue by berserkore** [Ullink/simple-slack-api#110]
There are two missing classes into the source preventing the sample to compile.

Missing classes:
- SlackPreparedMessage.java
- EmojiSlackReply.java

Regards

**Comment by berserkore** [comment]
Missing severals methods in SlackAttachment. Seems that https://github.com/Ullink/simple-slack-api/tree/master/sources/src/main/java/com/ullink/slack/simpleslackapi not the same has the current library 0.5.1
is It normal?

Cheers

**Comment by gluck** [comment]
They will be in 0.5.2 (unreleased yet), but you can pull a SNAPSHOT version in the meantime if you need them.
