### ISSUE TITLE
No existing way to get the Team name by the bot?

### ISSUE THREAD

**Issue by bholagabbar** [Ullink/simple-slack-api#117]
I did not find any way to get the team associated with the bot. Like *teamname*.slack.com. Is there any way to do this currently?

**Comment by bcorne** [comment]
For now it's not available, but it shouldn't be that hard to implement, the information is available in the JSON data provided during connection. I'll set it as an improvement and will handle that

**Comment by bholagabbar** [comment]
Uhh I'd love to issue a PR fixing the issue. Where should I make the
changes? If you could acquaint me with what's expected

**Comment by bcorne** [comment]
Oh, my bad, I've browsed the code and I think it is already available: you can get it by retrieving the team properties in your SlackSession instance with getTeam() and the team has the getDomain() method which should give you the teamname value. Let me know if this is the data you're looking for.

Best regards,

Benoit

**Comment by bholagabbar** [comment]
@bcorne I don't see any getTeam() method from my `session` instance.
 
![screenshot from 2016-08-30 21-17-16](https://cloud.githubusercontent.com/assets/11693595/18096345/764b8858-6ef7-11e6-839b-82233f19aaf7.png)

**Comment by bcorne** [comment]
This was added by the end of June so no release was made available since. You can wait for the next release (I don't have any ETA) or use the last snapshot using jitpack

**Comment by bholagabbar** [comment]
@bcorne Maybe you could close this issue after the next release then :)

**Comment by bholagabbar** [comment]
@bcorne BTW the tool I built using your library is live! Check it out. I've given you credits too :) https://github.com/bholagabbar/irackbot . a star would be great :D

**Comment by bcorne** [comment]
That looks nice :+1: , I've starred it of course.
