### ISSUE TITLE
Feature Request images in messages

### ISSUE THREAD

**Issue by aaomidi** [Ullink/simple-slack-api#12]
thumb_url and image_url in SlackAttachement

**Comment by bcorne** [comment]
I'll have a look at that (as well as the new emoji reactions recently added)

**Comment by aaomidi** [comment]
I've added it in my fork, but I accidently committed a lot of extra stuff with it so I can't make a PR
But if you want a link: 
https://github.com/aaomidi/simple-slack-api/blob/bf881bb4e64e55fc931ef2e01d7335f385939ba1/src/main/java/com/ullink/slack/simpleslackapi/SlackAttachment.java
and
https://github.com/aaomidi/simple-slack-api/blob/bf881bb4e64e55fc931ef2e01d7335f385939ba1/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackJSONAttachmentFormatter.java

**Comment by bcorne** [comment]
Ok fine I'll look at that then, thanks a lot :)

**Comment by bcorne** [comment]
I've done the merge in the 0.4.3 version
