### ISSUE TITLE
tyrus and websockets dependencies are not optional in release builds, but are in commit-pinned builds

### ISSUE THREAD

**Issue by clenart** [Ullink/simple-slack-api#120]
tyrus and websockets dependencies are not optional in release builds, but are in commit-pinned builds

https://jitpack.io/com/github/Ullink/simple-slack-api/0.6.0/simple-slack-api-0.6.0.pom

vs.

https://jitpack.io/com/github/Ullink/simple-slack-api/5defbf5018b42f94844f39e10973cde8ea5b6ea8/simple-slack-api-5defbf5018b42f94844f39e10973cde8ea5b6ea8.pom
# 

compounded with [gradle not supporting the maven optional field](https://issues.gradle.org/browse/GRADLE-1749), this means that 0.6.0 works out of the box, whereas 5defbf5018b42f94844f39e10973cde8ea5b6ea8 requires user of the library to manually include tyrus and websockets in their dependencies.

**Comment by jgangemi** [comment]
i just hit this myself trying to build from sources and adding the `1.0.0-SNAPSHOT` version to my project. is there a reason those two dependencies are declared as `optional` in the first place?

**Comment by dkowis** [comment]
I have also run into this problem. I have removed the optionalness from it in this pull request: #181

**Comment by dkowis** [comment]
It's in master now, can probably be closed.
