### ISSUE TITLE
consider removing guava or using a shaded jar

### ISSUE THREAD

**Issue by jgangemi** [Ullink/simple-slack-api#126]
the dependency on guava makes things a little difficult if one wants to use `19.0` as the releases are usually not backwards compatible. someone could also be locked into a version prior to `18.0`.

obviously this library needs to have it's dependencies to function, so if it's not possible to break that dependency, please consider moving to a shared jar (and make sure you adjust the weird transitive deps that are still being pulled in, cough junit, logback cough) so consumers of the library are able to use whatever libs are necessary for their app.

**Comment by jgangemi** [comment]
also the pom that is part of maven central has all the dependencies listed as `runtime` which makes overriding more difficult.

**Comment by bcorne** [comment]
About Guava, it's already planned to be removed on the next version, a very small part of it is actually used. About the maven pom, I'll have a look at how it is generated to have nicer dependencies

**Comment by velo** [comment]
Suggest closing this ticket

**Comment by bcorne** [comment]
yup, thanks
