### ISSUE TITLE
addchannelCreatedListener

### ISSUE THREAD

**Issue by maystrovyy** [Ullink/simple-slack-api#135]
1. method doesn't work!
2. needs to camelCase rename "addChannelCreatedListener"

**Comment by bcorne** [comment]
Ok, I'll have a look at this

**Comment by maystrovyy** [comment]
Waiting for your answer. 
We can discuss it together (skype, slack or another).

**Comment by bcorne** [comment]
done for camel casing the method, what's happening when you're calling the method (why doesn't it work) ?

**Comment by maystrovyy** [comment]
@bcorne thank you very much for camel case fixing. When i tested this listener he simply he wasn't listened the creation of chat.
