### ISSUE TITLE
SlackSession shouldn't import impl package

### ISSUE THREAD

**Issue by clenart** [Ullink/simple-slack-api#136]
https://github.com/Ullink/simple-slack-api/blob/08407669a70810e8ed8b0e4f4b0f6f5103364523/sources/src/main/java/com/ullink/slack/simpleslackapi/SlackSession.java#L4

importing for SlackChatConfiguration

**Comment by bcorne** [comment]
indeed, there's something to change here: impl pakage content shouldn't be accessed from outside classes

**Comment by bcorne** [comment]
done in 3afb8fdeda13bfccf4650209491367e4a7855bdd
