### ISSUE TITLE
parse json when detecting pongs

### ISSUE THREAD

**Issue by clenart** [Ullink/simple-slack-api#137]
https://github.com/Ullink/simple-slack-api/blob/0d6709d70d61a673689118a260bb8ad0f250d9ce/sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackWebSocketSessionImpl.java#L843

🙃

**Comment by clenart** [comment]
https://github.com/Ullink/simple-slack-api/pull/139

**Comment by bcorne** [comment]
merged :)
