### ISSUE TITLE
Update Cache Automatically

### ISSUE THREAD

**Issue by aggarwalankush** [Ullink/simple-slack-api#141]
https://github.com/Ullink/simple-slack-api/blob/master/sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackWebSocketSessionImpl.java#L283

If we see here, it's caching data in initial connection. It won't update unless I'm doing `session.disconnect() and session.connect()` again. Shouldn't you update the cache based on events https://github.com/Ullink/simple-slack-api#supported-slack-events?

for eg. add new channel to `channels` on `channel /private group joined event`

Doing this will automatically resolve following issues as well 
- https://github.com/Ullink/simple-slack-api/issues/138
- https://github.com/Ullink/simple-slack-api/issues/94

**Comment by bcorne** [comment]
Hi,

Yes indeed, the cahed data can be outdated if new channels or users are added / removed. The session should listen to users / channel changes

**Comment by yegor256** [comment]
@aggarwalankush I second this, have to disconnect/connect, which is not really how it should work

**Comment by bcorne** [comment]
Commit ef6be954461c949ec77f2a04beb4bbd6f2a97e8b should solve most of the issues raised here

**Comment by yegor256** [comment]
@bcorne can you please release a new version?

**Comment by bcorne** [comment]
I will release the 1.0.0 version soon, but since it has some breaking changes, I'd like to fix some more issues. In the meantime you can still use the last snapshot using jitpack : https://jitpack.io/#Ullink/simple-slack-api

**Comment by gezerk** [comment]
I see that this issue is marked closed and will soon be released.  Should [#94]( https://github.com/Ullink/simple-slack-api/issues/94) be closed as well?
