### ISSUE TITLE
Add reaction to message

### ISSUE THREAD

**Issue by jsutaria** [Ullink/simple-slack-api#146]
I currently have a listener set up for when users send messages, and have a filtering so that it only continues through if the message is qualified. How would I be able to add an emoji reaction to this message that was just sent?

**Comment by bcorne** [comment]
Hi,

I've already developed this kind of feature in a side project, you can have a look at this class which is doing I think what you'd like to achieve : 

https://github.com/Ullink/slack4gerrit/blob/master/src/main/java/com/ullink/slack/review/ReviewMessageListener.java#L50

Best regards,

Benoit

**Comment by jsutaria** [comment]
Thanks! Works perfectly as I wished.

**Comment by bcorne** [comment]
glad to help :)
