### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by ProRival** [Ullink/simple-slack-api#147]
Hello, 
I'm trying to use the simple-slack-api, however there is no way to turn off the slf4j logger. It spams my console and I don't really care about DEBUG logs. Can you (the developers) please tell me a way to disable the logging? 
![screenshot_2016-11-28_18-40-03](https://cloud.githubusercontent.com/assets/15129974/20693741/fef6201a-b5a5-11e6-9ae1-0d9f8bd8a2fc.png)

**Comment by afilhodaniel** [comment]
I'm interest in this question too

**Comment by yegor256** [comment]
@ProRival just configure your logging facility to suppress `DEBUG` logging level of this particular package.

**Comment by bcorne** [comment]
the library is pushing to slf4j as much log as it can. It's up to your logging library to narrow down what you need in logs. If for example you are using the simple logger from slf4j, you'll just have to add a simplelogger.properties file in your classpath with the following line in it: 

org.slf4j.simpleLogger.defaultLogLevel=info

**Comment by ProRival** [comment]
I did that. Didn't work.

**Comment by ProRival** [comment]
Thank you anyway.

**Comment by bcorne** [comment]
Which logging framework are you using?

**Comment by sic2** [comment]
Same problem here.
Using log4j, I have tried to setup something like this:
`log4j.logger.com.ullink.slack=ERROR`

or like this: `org.slf4j.simpleLogger.defaultLogLevel=ERROR`

but none of these have worked

**Comment by sic2** [comment]
**SOLVED**

The simple slack api attempts to add another logger to the one I already had and this was messing things up.
So, first I run `mvn dependency:tree` to check what other loggers were around, then I excluded the logger from the dependency like this:

```
<dependency>
            <groupId>com.github.Ullink</groupId>
            <artifactId>simple-slack-api</artifactId>
            <version>0.6.0</version>

            <exclusions>
                <exclusion>
                    <groupId>ch.qos.logback</groupId>
                    <artifactId>logback-classic</artifactId>
                </exclusion>
            </exclusions>
 </dependency>
```

Finally, I set one line in the log4j.properties file as:
`log4j.logger.com.ullink.slack.simpleslackapi=ERROR`

I hope this will help others

**Comment by bobmk2** [comment]
This library uses `logback-classic`, so I put `logback.xml` and be able to control log level 😄 

### my setting

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE logback>
<configuration>
    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg</pattern>
        </encoder>
    </appender>

    <root level="info"> ## Change this ##
        <appender-ref ref="STDOUT" />
    </root>
</configuration>
```
