### ISSUE TITLE
Upload newest version to Maven Central

### ISSUE THREAD

**Issue by BenRomberg** [Ullink/simple-slack-api#15]
We'd like to use some of the newest features, like coloring for attachments. Unfortunately, the newest version available on Maven Central is only from May, not including some of the latest changes.

It would be awesome if you could upload a new version to Maven Central, so we can easily benefit from the latest changes.

**Comment by bcorne** [comment]
Hi,

That's still in snapshot but I can deliver a new snapshot version if you want (hope to do that today). 

I still need to test these features and before releasing a new final version I plan to add a way to use reaction emoji (that should'nt take that much time anyway)

Best regards.

**Comment by BenRomberg** [comment]
That would be awesome - if you could release it by the end of the week that would be totally sufficient.

Thanks!

**Comment by bcorne** [comment]
For now I've uploaded a new snapshot version on oss.jfrog.org. I hope it'll be fine for you.

Best regards,

Benoit

**Comment by bcorne** [comment]
0.4.3 released and available on maven central, with all the things you asked for :)

**Comment by BenRomberg** [comment]
Cheers mate!
