### ISSUE TITLE
Slash Command Message Post Listener

### ISSUE THREAD

**Issue by k1201abak** [Ullink/simple-slack-api#151]
I would like to implement Slack Bot that will reply to /giphy message . There is no event listener that I can use to listen the event like /command

**Comment by bcorne** [comment]
Hi,

This is actually not possible to implement with this library. The Slack RTM api doesn't provide any access to slash commands events. You can build your own slash command by having an HTTP server listening to requests sent by Slack you'll have more information here : https://api.slack.com/slash-commands
