### ISSUE TITLE
SlackChannelReply.slackChannel is null when slackSession.joinChannel

### ISSUE THREAD

**Issue by sixcorners** [Ullink/simple-slack-api#154]
This is the reply object I see
slackChannelReply = {SlackChannelReplyImpl@12330} 
 slackChannel = null
 ok = true
 error = null

https://api.slack.com/methods/channels.join
The sample response seem to include the channel.

Also after joinChannel is invoked with a new channel name slackSession.findChannelByName(channelName); still returns null until

    slackSession.disconnect();
    slackSession.connect();

is invoked.

**Comment by bcorne** [comment]
should be solved with #141
