### ISSUE TITLE
Add a SlackSessionWrapper

### ISSUE THREAD

**Issue by sixcorners** [Ullink/simple-slack-api#155]
SlackSession has a lot of methods. Implementing it requires implementing a lot of methods.
If there were a SlackSessionWrapper implemented in the same way that HttpServletRequestWrapper wraps HttpServletRequest then it would be easier to do certain things with this API.

For instance I seem to be forced to use this API through a wrapper like this:

		return new SlackSessionWrapper(SlackSessionFactory.createWebSocketSlackSession(token)) {
			@Override
			public synchronized SlackChannel findChannelByName(String channelName) {
				try {
					disconnect();
					connect();
				} catch (IOException e) {
					throw new RuntimeException(e);
				}
				return super.findChannelByName(channelName);
			}

			@Override
			public synchronized Collection<SlackChannel> getChannels() {
				try {
					disconnect();
					connect();
				} catch (IOException e) {
					throw new RuntimeException(e);
				}
				return super.getChannels();
			}
		};

**Comment by bcorne** [comment]
Done with commit 56882637af2a36c60b70046074628ff12482ff6c
