### ISSUE TITLE
'No website or description provided'

### ISSUE THREAD

**Issue by bholagabbar** [Ullink/simple-slack-api#156]
I think the repository should add a github description. We can copy the one from slack `A Slack client library in Java`

**Comment by bcorne** [comment]
Nice idea, I'll work on that, thank you :)

**Comment by bholagabbar** [comment]
yeah, It's just one line you need to add in the repository lol :)

**Comment by bcorne** [comment]
that's also a matter of rights (that I don't have) ;)

**Comment by gluck** [comment]
done !

**Comment by bcorne** [comment]
👍
