### ISSUE TITLE
Enabling a listener to remove itself results in ConcurrentModificationException

### ISSUE THREAD

**Issue by joeltoby** [Ullink/simple-slack-api#158]
Use-case: application needs to listen for one specific event to occur.  Once the event has been handled, the listener should be removed so that the handler isn't triggered for any future events of that type.  The easiest way to do this is for the event handler to remove itself.

The listeners are in a `List` and the events are dispatched by iterating the list as follows:
```

for (L listener : listeners) {
  try {
    listener.onEvent(event, SlackWebSocketSessionImpl.this);
  } catch (Throwable thr) {
    LOGGER.error("caught exception in dispatchImpl", thr);
  }
}
```
([ SlackWebSocketSessionImpl.java#dispatchImpl ](https://github.com/Ullink/simple-slack-api/blob/3afb8fdeda13bfccf4650209491367e4a7855bdd/sources/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackWebSocketSessionImpl.java))

This of course results in a `ConcurrentModificationException`.  Should an iterator be used instead, or is there another preferred way to do this?

Example:

```
ReactionAddedListener reactionAddedListener = new ReactionAddedListener() {
        @Override
        public void onEvent(ReactionAdded event, SlackSession session) {
          // do something here
          session.removeReactionAddedListener(this);
}
```

**Comment by bcorne** [comment]
fixed with 08a55eb648da64f824379f758e3ddbd133e6bfe3
