### ISSUE TITLE
How to disable debug info?

### ISSUE THREAD

**Issue by RoccoDeveloping** [Ullink/simple-slack-api#161]
Hey there!
I'm running a Minecraft server with this API, but the debug info is too spammy.
Is there a way to disable getting debug info?

**Comment by bcorne** [comment]
Hi,

The library is providing as much log info as possible, that's up to the log consumer to setup the level of log it needs. I had a quick look at minecrafts servers logging library, it appears it is using log4j. 

Here are some links on how to configure log4j in your server so you will be able to reduce the amount of log displayed: 

http://evilseph.com/post/69715062422/taming-minecraft-servers-log4j2-basics
http://www.journaldev.com/7128/log4j2-example-tutorial-configuration-levels-appenders

Best regards,

Benoit

**Comment by RoccoDeveloping** [comment]
Thank you for the reply. However, I managed to get it to work by following the closed issue named  "Logging".
Thank you anyway.

**Comment by bcorne** [comment]
no problem, enjoy the library :)
