### ISSUE TITLE
NPE during parse JSON field 'user'

### ISSUE THREAD

**Issue by Ivana-** [Ullink/simple-slack-api#163]
When sending a Thread message in Slack, an websocket event about it occurs (not only event about message itself with its text/user/etc, but additional event about a fact of reply on existing message), and in its json there is no field 'user' in first level of fields (it lays deeper in json structure). During parsing this event occurs an exception (code trys to define user in 4 ways, and if it is not defined, throws an exception), websocket fails and reconnects, an events about recent events are received again and other bad things takes plase.

**Comment by bcorne** [comment]
Hi, without at least the stack trace I won't be able to find out the issue
