### ISSUE TITLE
multiple responses for a single input query from the slack bot

### ISSUE THREAD

**Issue by sethu424** [Ullink/simple-slack-api#164]
Hi,
Quite often I end up seeing multiple duplicate responses for a single input message from my chat bot. I end up restarting the java process every time to overcome this issue. 

Can this happen when multiple users talk to the slack bot at the same time?

Thanks in advance,
Sethu
![error](https://cloud.githubusercontent.com/assets/8466784/22780053/391c11c0-eee3-11e6-9f7d-2684cdf011f9.png)

**Comment by codelibra** [comment]
I am facing the same problem. Same response multiple times, it happens infrequently.
Unable to figure the root cause here.

**Comment by fredbradley** [comment]
Just passing through whilst looking for an answer myself for something... 

Your errors are usually caused by the slackbot being run twice. (Each time the piece of code that is running the bot is called you'll get a response!)

**Comment by pcornish** [comment]
Might also be caused by https://github.com/Ullink/simple-slack-api/issues/180

**Comment by bcorne** [comment]
#180 being fixed, should be fine now
