### ISSUE TITLE
No way to fetch a single message

### ISSUE THREAD

**Issue by shanness** [Ullink/simple-slack-api#165]
As per the docs :-
https://api.slack.com/methods/channels.history
> To retrieve a single message, specify its ts value as latest, set inclusive to true, and dial your count down to 1.

This requires taking a messageID (timestamp) which none of the methods do.

My use case is that I need the message text that a user reacts to.

**Comment by shanness** [comment]
Here's an impl of it.  Tested and working.  

https://github.com/shanness/simple-slack-api/commit/911537a8da589da25b584302cad1215ec92ac9c0

Doesn't work with non user messages (i.e. bot messages etc) due to this :-
```
if (GsonHelper.getStringOrNull(event.get("subtype")) == null) {
       messages.add((SlackMessagePosted) SlackJSONMessageParser.decode(session, event));
}
```
Not sure of the thinking there.

**Comment by saikek** [comment]
Pull request on this one ?

**Comment by bcorne** [comment]
Done with cbbe175b1e935cff24e9ea3a8b55995f109cd04c
