### ISSUE TITLE
Is that possible to send message to thread

### ISSUE THREAD

**Issue by leequanfu** [Ullink/simple-slack-api#172]
Hi guys,

Is that possible to send message to threads in channel? Slack seems support it https://api.slack.com/docs/message-threading.

**Comment by Omertron** [comment]
I would like this feature too

**Comment by anojansivarajah** [comment]
As this feature is merged now, can we have a release with this feature? @logscl

**Comment by outofcoffee** [comment]
Hi @logscl, I'm the maintainer of a downstream project - corebot: https://github.com/outofcoffee/corebot

We came across this feature addition thanks to @anojansivarajah - would you be able to give us an idea of when your next release will be?

Many thanks,

Pete

**Comment by logscl** [comment]
Hello @anojansivarajah and @outofcoffee,

Unfortunately, I'm not a maintainer of this project - I just committed a couple of features. I don't know when this feature will be released.

You'll have to either build your own version and put it into your local repository or wait for the next release.

If you want to know when the next version will be released, I suggest you to contact one of the maintainers (@bcorne or maybe @gluck).

Regards,

Logan

**Comment by dkowis** [comment]
You can use jitpack, if you've got that ability.

https://jitpack.io/#Ullink/simple-slack-api

For any branch, or tag jitpack will provide the built library.
