### ISSUE TITLE
Lots of warnings on UNKNOWN event in 1.0.0

### ISSUE THREAD

**Issue by rdifalco** [Ullink/simple-slack-api#183]
I get a ton of these. If they are expected should they be warnings? If they are not expected shouldn't you have a `#toString` method on `SlackEvent`? I'm pretty sure I get them each time I send a message, but the message post seems to be successful. 

```
event of type UNKNOWN not handled: com.ullink.slack.simpleslackapi.events.SlackEvent$1@33fe96a4
```

**Comment by pvangool** [comment]
I see the same. In my case, it is for events of type 'desktop_notification'. The library doesn't support them.

**Comment by darcatron** [comment]
I'm seeing a bunch of these too. Agree with rdifalco that they shouldn't be printed as warning (I'd prefer they aren't printed at all)

**Comment by dominic-miglar** [comment]
:+1:

**Comment by bcorne** [comment]
This is now logged following this commit : a79f99f9bc9d6f5257b297b2661560ada322e063
