### ISSUE TITLE
Bot is receiving the same event twice

### ISSUE THREAD

**Issue by pvangool** [Ullink/simple-slack-api#184]
Hi,

I'm using v1.0.0 at the moment. But v0.6.0 gives hte same result.

When I use the ListeningToMessageEvents sample code I see that every posted message is received twice by my bot. I turned on debug and it seems like there are 2 websocket connections. See the attached log snippet.

[debug.txt](https://github.com/Ullink/simple-slack-api/files/1069894/debug.txt)

Is anybody else seeing this?

Thanks.

Paul

**Comment by pcornish** [comment]
Hi @pvangool - could it be caused by this issue: https://github.com/Ullink/simple-slack-api/issues/180 ?

**Comment by bcorne** [comment]
this is certainly caused by #180
