### ISSUE TITLE
Unable to send msg to a specific channel

### ISSUE THREAD

**Issue by JamesKelley** [Ullink/simple-slack-api#19]
When I connect to slack via this API

SlackSession ss = SlackSessionFactory.createWebSocketSlackSession("xxx");
ss.connect();

I get the following output:

asoiaf
data-quality-planning
design
development
fabrica_builds
general
hn
implementation
jira-notifications
meeting-notes
project-admin-todo
qa-webtool
random

Listing all the channels for our account.

If the following is executed:
ss = sendMessageOverWebSocket(slackSession.findChannelByName("general"), "Hello world", null);

"Hello world" appears on the "general" channel in Slack

BUT, if *ANY* other channel is selected, (for example: replace "general" with "hn")

 I get the following error: 
 [Grizzly(2)] DEBUG com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl - receiving from websocket {"type":"error","error":{"code":0,"msg":"invalid channel id"}}

The following code was executed:

Collection<SlackChannel> channels = slackSession.getChannels();
logger.info("Number of slack channels found is " + channels.size());
for(SlackChannel sc : channels)
{
	system.out.println(sc.name());
}

The number of channels and the list of names for each channel is properly shown.

Suggestions?  
James
(jk@jtkdev.org)

**Comment by bcorne** [comment]
Hi,

It might be due to the fact the bot hadn't subscribe to this channel (or wasn't invited) (by default everybody is in "general"). 

Is it a channel or a private group?

Best regards,

Benoit

**Comment by JamesKelley** [comment]
I want to send msgs to a particular channel (in this case cip-server).  Do I subscribe programmatically or by using the web interface provided by SLACK?

What is the process of subscribing using the API (I don't see any information about how this would be done?)   Can you point me in the right direction?

**Comment by JamesKelley** [comment]
I believe there is some sore of process of having your BOT join a channel but it is not properly documented. I have searched the developer API which make mention that this process exists but doesn't actually explain how to do this. Can you perhaps add a line to two in you docs to indicates where/how this "Join" process actually works?

**Comment by bcorne** [comment]
I'll reopen it so I keep it as a remainder. I will add some methods to allow a bot to join/leave channels and add some docs. In the meantime you can invite the bot to a channel using a standard Slack Gui. 

Best regards,

Benoit

**Comment by bcorne** [comment]
join / leave channel commands are now available with version 0.4.5
