### ISSUE TITLE
Proxy conf > Support of jre -Dhttp.* properties ?

### ISSUE THREAD

**Issue by adriens** [Ullink/simple-slack-api#192]
Hi,

i'm begining to test some some code at home and everything works just fine !

At the office, we have to deal with as authenticated (OLFEO/Squid based proxy)... and thanks to #176 it seemns like it can be setup this way....but this means i will have to deal with proxy conf in the code.

I had to deal with this kind of constraint on a lot of java projects...nad i used to use the -Dhttp. jvm options :

https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html

Hence the question is : does the lib support these jvm options out of the box ?

Thanks in advance for your answser.
Kind regards and thanks for this very easy to use lib !

**Comment by bcorne** [comment]
Hi, Since the library is relying on third party libraries for the connectivity part, I did not checked that. The best way to know is to try.
