### ISSUE TITLE
Installing simple-slack-api in Netbeans 8.2 (ubuntu 16.04)

### ISSUE THREAD

**Issue by Praveenv98** [Ullink/simple-slack-api#214]
Hey Guys !
I'm PraveenVelliengiri , a student from India. Actually I'm interested in building a project(college project) using simple-slack-api library. The aim of the Project is to transport  the development steps of user in a clearly visible and simple graphs to others using via SLACK. I like your library but I don't know how to use it.

1.)  How to build the Simple-slack-api library with my Netbeans ? 
2.)  Is there any .jar files so that I can directly add it to my project ?
Netbeans IDE - 8.2
Computer os  - ubuntu 16.04  
I have downloaded the zip file, but I don't know how to build the library using zip in netbeans. 
I kindly request you to provide some insights on this Guys...
I also hope that you will provide good support over the mean time.

**Comment by Praveenv98** [comment]
whether this is absolute necessary to have all runtime dependencies .jar file ? I think if i want to use simple slack api whether i want to download all the dependencies jar files ? 
I mean dependencies as in the list:
https://mvnrepository.com/artifact/com.ullink.slack/simpleslackapi/1.0.0
Thanks

**Comment by bcorne** [comment]
You'll need all the runtime dependencies, not everything is bundled in the provided jar
