### ISSUE TITLE
can't build project

### ISSUE THREAD

**Issue by Geanik** [Ullink/simple-slack-api#219]
hello
i'm not sure if i'm simply to dumb but i cant get this project running

i cloned it and opened it with IntelliJ and Eclispe, but neither of them lets me build the project ans gives me hundreds of errors

e.g.:
- lots of final mebers that don't get set
- lots of methods that don't get found

has anyone experienced the same, or is it me?

thx for help

**Comment by Geanik** [comment]
my reason for forking is that i want to extend the sendFile() methods
for example one for codeSnippets where you can define the language
or another one for sending images by giving a File parameter(i know this possible by simply giving the byte[] of the image as parameter, but i want cleaner code)

**Comment by bcorne** [comment]
I think that might be linked to the usage of [lombok](https://projectlombok.org/), IntelliJ has a lombok plugin you can use so you'll be able to build the project

**Comment by Geanik** [comment]
thx a lot <3
now it works
