### ISSUE TITLE
Post direct message (message to user) implemented?

### ISSUE THREAD

**Issue by malteBehrendt** [Ullink/simple-slack-api#22]
I'd love to get the direct channels using https://api.slack.com/methods/im.list but I didn't find a corresponding method. 

Is this on purpose?
Is there a workaround?

Thanks!

**Comment by bcorne** [comment]
Hi,

It's not on purpose and  I don't think it could be workarounded with the actual code but such a feature could be added to the library (but I'm away from my computer until the end of August), I'll have a look at this as soon as I have some time.

Best regards

Benoit

**Comment by malteBehrendt** [comment]
Hi Benoit,

thanks for having a look at it next month! 
I hope you're enjoying a nice vacation right now :D

Best regards,
Malte

**Comment by dseebacher** [comment]
There is (still) no separate handling of im channels, but with the next release im channels will be part of the general channel list.

```java
session.getChannels().stream().filter(c -> c.isDirect()).forEach(im -> ...);
```

**Comment by malteBehrendt** [comment]
Nice, thanks! 

Please let me know if this functionality is on Github (before an official release), I'll be happy to test :D

**Comment by dseebacher** [comment]
It's on master. Let me know if it works as expected :)

**Comment by malteBehrendt** [comment]
Great, will try it tomorrow noon :)

**Comment by dseebacher** [comment]
@malteBehrendt 
I guess we can close the issue?

**Comment by bcorne** [comment]
yes of course :)  thanks again
