### ISSUE TITLE
MessageSubType does not contain if the messages was read 

### ISSUE THREAD

**Issue by GaborCsikos** [Ullink/simple-slack-api#220]
I want to know if the message was read in the channel.
SlackMessagePosted does not contain any field for that, and nor does the MessageSubType.

Is it a way to determine that a message was read? (I retrieved all the messages with ChannelHistoryModule.fetchHistoryOfChannel method).

**Comment by bcorne** [comment]
For now it is not supported. That kind of information provided by the https://api.slack.com/methods/channels.info method ("last_read" field)

In the meantime you can still call that method using the postGenericSlackCommand method (https://github.com/Ullink/simple-slack-api/blob/master/sources/src/main/java/com/ullink/slack/simpleslackapi/SlackSession.java#L130) and parse the response to fetch that information.

Best regards,

Benoit
