### ISSUE TITLE
Code sample > Mention someone while sending a message to  a channel

### ISSUE THREAD

**Issue by adriens** [Ullink/simple-slack-api#225]
Hi,

i was looking for a code sample that shows how to post a message in a channel (this could be easily done), but also, to mention someone in the message body : for now, writing the @buddy text does not do the trick, while when i do it by hand it works. Looks like something has to be done.
For now, adding emojis withs codes is ok, but the @someone tag does not : would have any code sample that makes it possible ? I don't want a directCHannel message, but to post that in a common channel.

Thank you in advance for your help.

Kind Regards,

Adrien

**Comment by adriens** [comment]
Basically, i need to do something like that : https://stackoverflow.com/questions/40771924/how-to-mention-user-in-slack-client

**Comment by bcorne** [comment]
<@" + user.getId() + "> should do the trick. You can find more about text formatting here: https://api.slack.com/docs/message-formatting

**Comment by adriens** [comment]
Yep, thanks !
