### ISSUE TITLE
New Maven Central Version

### ISSUE THREAD

**Issue by hcherndon** [Ullink/simple-slack-api#23]
Greetings,

Do you mind pushing a new build to Maven Central? Some recent changes I'd like to have without having the whole project pulled.

Thanks,
Holt Herndon

**Comment by bcorne** [comment]
Hi, 

I'll do that soon, maybe this week (I can also push a new snapshop version), what kind of changes would you like to use?

Best regards,

Benoit

**Comment by Elphame** [comment]
Hi,

I'm interested in a new build to Maven Central too =)

Thanks to make it soon =)
Caroline

**Comment by bcorne** [comment]
Then I'll do my best :)

**Comment by bcorne** [comment]
I've released the 0.4.5 version, this should be available soon on maven central.

**Comment by hcherndon** [comment]
Thanks a lot mate!
