### ISSUE TITLE
Some user fields are not exposed

### ISSUE THREAD

**Issue by candrews** [Ullink/simple-slack-api#27]
SlackUser should have these fields added to it, as they are included in the Slack API's JSON (and appear in https://github.com/Ullink/simple-slack-api/blob/841f4ad7cd8a531a47e45beeebb1e7e79e0d4549/src/test/resources/test_json.json ):
* tz
* tz_label
* tz_offset

These fields would be very useful to me - can you please add them?

**Comment by bcorne** [comment]
Hi, 

Of course I can add that. I leave the issue open as a reminder

**Comment by bcorne** [comment]
just pushed on the repo

**Comment by candrews** [comment]
@bcorne can you publish a new version to Maven please?

And thank you so much! That was quite fast :)
