### ISSUE TITLE
Publish new version to Maven

### ISSUE THREAD

**Issue by candrews** [Ullink/simple-slack-api#28]
Can you please publish a new version to maven so recent changes (specifically #25, #26, and #27) can be accessed?

Also, are you publishing snapshots anywhere?

Thanks again!

**Comment by bcorne** [comment]
Hi,

I plan to do such a release by tomorrow.

About snapshots, I publish sometime some snapshot versions on oss.jfrog.org but I still lack a way to have them on maven central.

Best regards,

Benoit

**Comment by bcorne** [comment]
Hi,

This might take a little bit more time since I have some trouble to synchronize the new version with maven central but I think it's a matter of days.

Best regards,

Benoit

**Comment by bcorne** [comment]
version 0.4.6 is now available on maven central :)
