### ISSUE TITLE
support for reactions

### ISSUE THREAD

**Issue by ggs-jan** [Ullink/simple-slack-api#30]
hi,

i like your simpleslackapi a lot.
would it be possible to add support for listening to reactions to messages in a channel?
or can you tell me if slack provides this feature via it's api?
it would be very helpful.

best regards,
jan

**Comment by ggs-jan** [comment]
it seems to be supported by their api: https://api.slack.com/methods/reactions.list

**Comment by bcorne** [comment]
Hi,

yes, I just saw that: 

https://github.com/slackhq/slack-api-docs/blob/master/events/reaction_added.md

I can add a listener to this kind of event when I'll have some time if you want.

Best regards,

Benoit

**Comment by ggs-jan** [comment]
Hi,

yes, that would be great. My plan is to listen to reactions on a channel.

Best Regards,
Jan

**Comment by reilost** [comment]
I had add reactions api support for our slack bot..
When I finish it ,i will commit a pr ^_^

**Comment by bcorne** [comment]
You rock!!! 

Then I'll publish a new version then

Thanks a lot

**Comment by reilost** [comment]
:crying_cat_face: 
yeah, I will do it  during the rest of travel ,lol...
Just finish the listener of reaction add at rome ..

**Comment by bcorne** [comment]
You lucky, enjoy your stay there :)

**Comment by olkoza** [comment]
If you don't want to clutter your vacation with that I implemented the listener together with getting a (self-updating) history of a channels messages including reactions. Lemme know if you are interested :)

**Comment by bcorne** [comment]
Hi olkoza, 

Sorry for the late reply, either solution is good. I'll be glad to have a look to your pull request.

Best regards,

Benoit

**Comment by olkoza** [comment]
Ok, I'm kinda packed at the moment, i will overlook my code at the end of next week and make it pretty and the do a PR :)

**Comment by bcorne** [comment]
Ok fine, 

Then I think a 0.5 release could be done.

Many thanks

**Comment by bcorne** [comment]
Hi, 

Any feedback about your plan to support the reactions events ?

Best regards,

Benoit

**Comment by olkoza** [comment]
Hey man,

sorry, I am really crunched at work atm, and as soon as something works,
you know ^^ .... But I will have a look at it on Thursday, promise. I
implemented the events, as well as the functionality to retrieve a
self-updating list of a channels history as well as the functionality to
message a user, i just need to refactor it a little bit, then you can have
a look.
By the way, did you ever think about getting rid of the naming convention?
I mean if you prefix every class with "Slack", you might as well leave the
Prefix out.

Best
Ole

2015-11-18 14:47 GMT+01:00 Benoit Corne <notifications@github.com>:

**Comment by bcorne** [comment]
Hello,

no pressure, take your time, we all have our busy times :) . Regarding the naming convention I'll have a look at what can be done. It'll cause a lot of compatibility issue (easily fixable) for people upgrading to a new version with a new naming convention. i have to think about it.

Best regards,

Benoit

**Comment by bcorne** [comment]
reactions were added with #47
