### ISSUE TITLE
isOk() in ParsedSlackReply is difficult to use

### ISSUE THREAD

**Issue by drahti** [Ullink/simple-slack-api#39]
Hi
I just updated to version 0.5
You decided to move the isOk() method from SlackReply to ParsedSlackReply. However no handle or Reply returned by SlackSession is related to ParsedSlackReply. 
That means that whenever I want to check isOk() I need to cast my SlackReply to ParsedSlackReply and check isOk() then.
Did I miss something or is this the preferred approach?
If not, can you make isOk() easier to use?

**Comment by bcorne** [comment]
Hi Drathi,

That's certainly a miss in they way I did some refactor. I keep the issue open and will fix that asap .

Best regards

Benoit

**Comment by bcorne** [comment]
Ok, I've reworked the usage of ParsedSlackReply, this should be way easier to use now, please keep me informed if you still have some troubles with this.

Best regards,

Benoit
