### ISSUE TITLE
username and icon_url are ignored (because as_user is always true)

### ISSUE THREAD

**Issue by jguice** [Ullink/simple-slack-api#4]
See https://api.slack.com/methods/chat.postMessage

> Using the `as_user` argument requires the [client scope](https://api.slack.com/docs/oauth#auth_scopes). The `username`, `icon_url` and `icon_emoji` arguments are ignored if `as_user` is true.

as_user is always true in [SlackWebSocketSessionImpl.java](https://github.com/Ullink/simple-slack-api/blob/d00bd51ad83f9f25e9ea0e2899065e4bffdef8ca/src/main/java/com/ullink/slack/simpleslackapi/impl/SlackWebSocketSessionImpl.java#L217) :wink:

**Comment by bcorne** [comment]
Yes I noticed that, I'll provide a way to set explicitly the as_user param. Thanks a lot for the feedback

**Comment by jguice** [comment]
Thanks!  While you're in there it would be super to have access to icon_emoji too :)

> `icon_emoji`	`:chart_with_upwards_trend:`	Optional emoji to use as the icon for this message. Overrides `icon_url`.

**Comment by bcorne** [comment]
Yes, I'll have a look to that too then :)

**Comment by bcorne** [comment]
Ok, I've added the required code, the sendMessage signature has changed to take benefits of these new options.

**Comment by jguice** [comment]
Thanks!  Will you be pushing a new release to https://oss.sonatype.org/content/repositories/releases/com/ullink/slack/simpleslackapi/ ?

**Comment by bcorne** [comment]
I can push a snapshot version of 0.3.1

**Comment by bcorne** [comment]
The snapshot is available on : 

https://oss.sonatype.org/content/repositories/snapshots/com/ullink/slack/simpleslackapi/0.3.1-SNAPSHOT/
