### ISSUE TITLE
When using openMultipartyDirectMessageChannel, I get a ClassCastException

### ISSUE THREAD

**Issue by kushal** [Ullink/simple-slack-api#42]
java.lang.ClassCastException: com.ullink.slack.simpleslackapi.impl.GenericSlackReplyImpl cannot be cast to com.ullink.slack.simpleslackapi.replies.SlackChannelReply

when calling .getReply().getSlackChannel()

(thanks for this great library, btw!)

**Comment by bcorne** [comment]
Ok I take it, 

thanks for your feedback,

Benoit

**Comment by ParaPenguin** [comment]
I'll see if I can fix this
