### ISSUE TITLE
Attachment not working

### ISSUE THREAD

**Issue by eSoares** [Ullink/simple-slack-api#48]
I'm unable to send attachment.
Is this a known bug?

----

This is how I'm connecting to the slack:
```
SlackSessionFactory.createWebSocketSlackSession("token");
```

When a new message is posted I reply with:
```java
session.sendMessageOverWebSocket(event.getChannel(), null, new SlackAttachment("test", "test", "test", "test"));
```

The generated JSON looks good:
> ```JSON
{
    "attachments": [
        {
            "pretext": "test",
            "text": "test",
            "title": "test",
            "fallback": "test"
        }
    ],
    "channel": "D0J38QR3L",
    "text": null,
    "type": "message"
}
```

But in Slack nothing shows up.

**Comment by bcorne** [comment]
Hi, sorry to be late to answer. 

Attachments should work (and they are in most cases since I'm using them every day) . I have to investigate your case.

Thanks for your feedback.

Best regards,

Benoit

**Comment by nishtahir** [comment]
If it helps, I seem to be having the same issue sending attachments using
```
session.sendMessageOverWebSocket("channel", null, attachment)
```

the log returns this

```
15:04:09.889 [Grizzly(1)] DEBUG c.u.s.s.i.SlackWebSocketSessionImpl - receiving from websocket {"type":"error","error":{"code":2,"msg":"message text is missing"}}
```

when I add a message, it's sent as a regular message without the attachment. 

On the other hand, 
```
session.sendMessage("channel", null, attachment)
```

works as expected.

**Comment by bcorne** [comment]
Oh, my bad, It is not possible to send attachments through the websocket connection (RTM API), but only with a standard HTTP request (what is done by sendMessage BTW) : 

It is specified here : https://api.slack.com/rtm

> The RTM API only supports posting simple messages formatted using our default message formatting mode. It does not support attachments or other message formatting modes. To post a more complex message as a user clients can call the chat.postMessage Web API method with as_user set to true.

**Comment by eSoares** [comment]
Thanks for the help, that works :smiley:
