### ISSUE TITLE
Session.connect failure

### ISSUE THREAD

**Issue by gsingers** [Ullink/simple-slack-api#5]
If the Slack session fails to connect, for instance due to a bad auth token, there is no way to know if you have a valid session or not.  It appears the connect() method silently swallows all exceptions.  It would be better to throw them so that we can fail early.

**Comment by bcorne** [comment]
yes, I'll fix that for the next version, thanks for the feedback

**Comment by bcorne** [comment]
I've commit a small change to throw the error on connect() failure.
