### ISSUE TITLE
Sending a message to a person in private? 

### ISSUE THREAD

**Issue by Taronyuu** [Ullink/simple-slack-api#52]
Is there an example to send a private message to a user? It should be possible according to the readme, but I'm unable to find how.

**Comment by bcorne** [comment]
Hi,

Once your session is connected to Slack you should be able to send a private message to a user using the following methods :

* session.sendMessageToUser(SlackUser user, String message, SlackAttachment attachment);
* session.sendMessageToUser(String userName, String message, SlackAttachment attachment);

Best regards,

Benoit.

**Comment by Taronyuu** [comment]
Thats it, thanks allot!

**Comment by bcorne** [comment]
You're welcome ;)
