### ISSUE TITLE
Reply as a Slack bot

### ISSUE THREAD

**Issue by KidCrippler** [Ullink/simple-slack-api#55]
I managed to build a bot that receives messages, but couldn't find a way to make it reply to the user who sent it the message (and only that user).

The method:
`session.sendMessageOverWebSocket()`
only accepts a SlackChannel, while you'd think that it should also accept a "SlackChat" or something like that.

The Slack API [supports this functionality](https://api.slack.com/methods/chat.postMessage#authorship).

I'm pretty sure that I'm missing something, because it has to be a very basic functionality, but for some reason I can't find a way to do it.

Help would be very appreciated,
10x

**Comment by bcorne** [comment]
Hi,

If you managed to get the message you should be able to reply to the sender using the information you got from the SlackMessagePosted event :

I imagine that to catch the message you implemented the SlackMessagePostedListener interface. So you should have access to the SlackMessagePosted object which not only contains the message itself but also the channel on which it was sent (It might be a bit confusing but there's no distinction here between IM, private group and open channels in the API, they are all represented by the SlackChannel class). If the message was sent directly to the bot (through an IM channel) then you can use the channel available in SlackMessagePosted to send your reply and it will be sent only to the user:

This kind of code should work
```
MyListener implements SlackMessagePostedListener {

   onEvent(SlackMessagePosted event, SlackSession session) {
             if (event.getChannel().isDirect()) { // to reply only to instant messages
                 session.sendMessageOverWebSocket(event.getChannel(),"my reply")
             }
    }
}
```

let me know if you still have some issues.

Best regards,

Benoit

**Comment by KidCrippler** [comment]
It worked, thanks a lot :-)

**Comment by bcorne** [comment]
glad to help :)
