### ISSUE TITLE
Unclear how to use event handlers?

### ISSUE THREAD

**Issue by Redrield** [Ullink/simple-slack-api#60]
So what I did which I thought would work, was make a class that implemented the listener I wanted to use, in this case, SlackMessagePostedListener. I implemented the onEvent, but when I passed the class to session.addSlackMessagePostedListener, it threw an error "Expression expected" So what do I do here?

**Comment by bcorne** [comment]
Hi, 

Where do you get this error message ? in the logs? do you have a stack trace or just this message? Would it be possible to have a look at what your listener is doing?

Best regards,

Benoit
