### ISSUE TITLE
why are member fields public?

### ISSUE THREAD

**Issue by jgangemi** [Ullink/simple-slack-api#63]
hi - i was wondering if there was a reason the member fields in the various classes are `public` instead of `private` and `final`.

thanks!!

**Comment by jgangemi** [comment]
also happy to submit a pull request to help adjust, just looking for a little background first.

**Comment by bcorne** [comment]
Hi,

If you have noticed some, then this should be a mistake and it wasn't done intentionally. I normally set the fields as private/protected and provide the required accessor methods (most of them being required by the implemented interfaces). 

So, if you want to fix it, be my guest :)

Best regards,

Benoit

**Comment by freesoft** [comment]
My PR #92 covers most of this issue along with other formatting and fix. Please check it and you can close this issue once PR is accepted.
