### ISSUE TITLE
Calling disconnect() does not end program, reconnects shortly afterwards

### ISSUE THREAD

**Issue by Redrield** [Ullink/simple-slack-api#65]
So I'm writing a bot that when a certain message is sent, it calls the disconnect method and ends. However, after the method is called the bot idles, then reconnects to the server. This is what the log looks like (Running through intellij) http://hastebin.com/kokasewoki.tex

**Comment by BobbyJohansen** [comment]
I am running into this issue now too, Attempting to close the session results in an attempt to reconnect.
