### ISSUE TITLE
retrieve attachment

### ISSUE THREAD

**Issue by Langleu** [Ullink/simple-slack-api#71]
Hello there,
how do I retrieve an attachment?
I have a messagePostedListener, which works fine, but sometimes other bots post attachments and I couldn't figure out yet how to retrieve the attachment and process it.
I tried getJsonSource, but this only returned me a null Object.
getMessageContent returned nothing.

**Comment by bcorne** [comment]
Hi,

I'm not sure it's been implemented yet (I don't remember to have handled that yet). I have to take a look at the code but it is definitely something which has to be supported. I'll look forward to solve this.

Best regards,

Benoit

**Comment by Langleu** [comment]
thanks, that would be really cool.
