### ISSUE TITLE
Question: Markdown on SlackAttachments

### ISSUE THREAD

**Issue by SenhorCastor** [Ullink/simple-slack-api#81]
Hi, I am trying to figure it out from the code how the Markdowns work, but I don't see where they are used.

Any example or idea of how to use them?

Thanks
Fer

**Comment by bcorne** [comment]
Hi,

Markdown support is very limited on Slack, you can find some more details here : https://get.slack.help/hc/en-us/articles/202288908-Formatting-your-messages

In the library when you're sending a message you can send string in "markdown like" format, it should be displayed with the according formatting

Best regards,

Benoit

**Comment by SenhorCastor** [comment]
I was trying to use markdown on an Attachment, as soon as I send the markdown on the title of the message it worked, thanks
