### ISSUE TITLE
Autoreconnect after failure (handle 504 Gateway Time-out)

### ISSUE THREAD

**Issue by Defozo** [Ullink/simple-slack-api#83]
After some long time of properly working... suddenly...
http://pastebin.com/4EkEUzQP
App crashes.

**Comment by freesoft** [comment]
The line 278 of com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.connectImpl as of today is

```
LOGGER.debug("retrieved websocket URL : " + wssurl);
```

and there is noting NullPointerException can be occur. You might need to specify which release you are using.

**Comment by gluck** [comment]
sounds like a duplicate of #108 which has more info :smile:
