### ISSUE TITLE
Newest Release

### ISSUE THREAD

**Issue by fhattl01** [Ullink/simple-slack-api#84]
Hi I just wanted to see when the newest version with sendFile will be up on Jitpack. Thanks!

**Comment by bcorne** [comment]
Hi,

It is already available on jitpack if you're using this dependency : 

com.github.Ullink:simple-slack-api:-SNAPSHOT

Best regards,

Benoit

**Comment by fhattl01** [comment]
Thank you!

**Comment by bartoleo** [comment]
Any idea when 0.6 will be officially released?

Thank you in advance
