### ISSUE TITLE
Issue in integrating library in existing project

### ISSUE THREAD

**Issue by HardikSuba** [Ullink/simple-slack-api#9]
I cannot add it as a module, I cannot add add it as a library too.

Android Studio 1.2.1.1
Android plugin version 1.0.0
Gradle version 2.2.1

**Comment by bcorne** [comment]
Hi,

I don't know well Android Studio but what's happening if you try to add it, you just can't or do you get an error?

Best regards

**Comment by HardikSuba** [comment]
Hi,
Thanks for replying.
I just can't add it. I tried to copy classes manually, I copied all dependency, but it is conflicting with other dependencies.

**Comment by bcorne** [comment]
Hi

I've just installed android studio, created a simple project and declared the libraries in the gradle script : 

````
dependencies {
    compile 'com.ullink.slack:simpleslackapi:0.4.0'
    compile 'org.glassfish.tyrus.bundles:tyrus-standalone-client:1.8.3'
    compile 'com.googlecode.json-simple:json-simple:1.1'
    compile 'org.slf4j:slf4j-simple:1.7.7'
    compile 'org.apache.httpcomponents:httpclient:4.4'
}
````

It seems to work (well at least I can access the library classes in my code). Could you give it a try?

Best regards

**Comment by bcorne** [comment]
no news, I hope this is fixed on your side.

**Comment by sirvon** [comment]
did you actually get this to work?

**Comment by bcorne** [comment]
Yes, as I said above, I installed android studio, created a simple project and declared the dependencies in the gradle script, If you still have the issue I reopen it
